update agenda of town hall
linkedin/datahub pull request #1982
Opened 2020-11-02 21:49 UTC by nagarjunakanamarlapudi

update agenda of town hall
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2020-11-02 21:51 UTC, mars-lan requested changes

2020-11-02 21:51 UTC, mars-lan commented on docs/townhalls.md
> +1. Lightning talk on Metadata use-cases at LinkedIn.
Please also tag people & give estimated time like https://github.com/linkedin/datahub/blob/master/docs/townhall-history.md

2020-11-03 00:29 UTC, nagarjunakanamarlapudi commented on docs/townhalls.md
> +1. Lightning talk on Metadata use-cases at LinkedIn.
Done

2020-11-03 00:49 UTC, keremsahin1 approved these changes

2020-11-03 00:55 UTC, jywadhwani approved these changes

2020-11-03 01:54 UTC, merged