feat(Search): Inject restli client into index builders
linkedin/datahub pull request #2024
Opened 2020-12-01 13:52 UTC by nagarjunakanamarlapudi

Inject restli client into index builders. Fixes #2023

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2020-12-01 21:50 UTC, hshahoss approved these changes

2020-12-01 22:00 UTC, jplaisted requested changes

2020-12-01 22:00 UTC, jplaisted commented on metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/IndexBuildersConfig.java
> +public class IndexBuildersConfig {
Please add javadoc to all new classes.

2020-12-02 22:03 UTC, jplaisted requested changes

2020-12-02 22:03 UTC, jplaisted commented on metadata-jobs/mae-consumer-job/src/main/java/com/linkedin/metadata/kafka/config/IndexBuildersConfig.java
> +   * @param restliClient Rest.li client to interact with GMS
Style nit: one line before `@param` block.

2020-12-03 04:49 UTC, jplaisted approved these changes

2020-12-03 19:43 UTC, merged