[React incubation] fixing browse routing
linkedin/datahub pull request #2069
Opened 2021-01-26 03:29 UTC by gabe-lyons

This regression was introduced by https://github.com/linkedin/datahub/pull/2060

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

2021-01-26 05:53 UTC, cptran777 commented
I'm confused as to how this wasn't caught in the previous PR. Is the application not throwing the typescript error when you try to build it?

2021-01-26 17:37 UTC, gabe-lyons commented
@cptran777 you're correct- it does throw a typescript error on build. Not sure exactly how it snuck in, it rode along in the last commit https://github.com/linkedin/datahub/pull/2060/commits/c79fb8b724fb8e96c6a4092991313faba3c958ff. We're going to set up some basic CI soon so issues like this won't be able to sneak by due to human error in the future.

2021-01-26 17:54 UTC, jplaisted commented
There's a build-and-test action that runs on every commit of every PR and just runs `./gradlew build`. Which, afaik, builds everything, right? 

https://github.com/linkedin/datahub/blob/master/.github/workflows/build-and-test.yml

2021-01-26 18:37 UTC, gabe-lyons commented
@jplaisted thanks for directing me to that. In that case we have two options

1) extend the build task to build the react app as well. Upsides: we dont need to add a new action. Downsides: if the react app CI breaks, it affects non-react prs

2) create a new action parallel to build-and-test that only runs on changes to datahub-frontend-react. Upsides: breakages in react won't affect non-react prs. Downsides: we have two CI actions.

Thoughts?

2021-01-26 18:41 UTC, shirshanka commented
My 2c : let's not allow the react app to be broken. 
So include the react app in the main gradle build.

2021-01-26 19:08 UTC, jplaisted commented
To be clear with gradle just add it to the `settings.gradle` file. It'll include it as a submodule, knowing it should build it and also treat it as a module in intellij, etc

2021-01-26 19:44 UTC, cptran777 commented
I agree, that even in incubation if there's such an obvious issue as "the react app doesn't build properly" that should prevent a PR from being merged.

2021-01-26 20:29 UTC, gabe-lyons commented
@jplaisted great- will do that in a followup.

2021-01-26 20:34 UTC, shirshanka commented
@gabe-lyons Maybe add it to this PR, so we know this PR is safe to merge ;)

2021-01-26 20:39 UTC, gabe-lyons commented
@shirshanka good idea- added

2021-01-27 07:20 UTC, cptran777 requested changes

2021-01-27 07:20 UTC, cptran777 commented on settings.gradle.bak
> +include 'datahub-dao'
Is this file intentional?

2021-01-27 17:27 UTC, gabe-lyons commented
@cptran777 removed 👍

2021-01-27 18:17 UTC, cptran777 approved these changes

2021-01-27 18:50 UTC, shirshanka approved these changes
LGTM! Thanks for reviewing @cptran777 :)

2021-01-27 18:52 UTC, merged