feat(ingestion): add option for optimized skipping of schemas
linkedin/datahub pull request #2209
Opened 2021-03-10 21:25 UTC by thomasplarsson

Fixes: #2208

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-03-10 21:30 UTC, thomasplarsson commented
@hsheth2 This is not the prettiest change I know, but I wanted to just put the PR out there to make any discussion about issue #2208 more concrete. For context, I am stumbling on this when trying to ingest from aws athena where we have in our non-production environment a truly polluted metastore with a ridiculous number of garbage schemas, whereas the number of schemas I would be interested in ingestion from is on the order of <10.

2021-03-10 23:21 UTC, hsheth2 requested changes
Overall looks pretty good! Made some minor suggestions

I ran into this same issue when I was ingesting from BigQuery, so I'm glad we've got a good solution for it

2021-03-11 07:39 UTC, thomasplarsson commented on metadata-ingestion/src/datahub/ingestion/source/sql_common.py
> +            if sql_config.schema_pattern.allowed(schema):
Agree and fixed.

2021-03-11 07:39 UTC, thomasplarsson commented on metadata-ingestion/src/datahub/ingestion/source/sql_common.py
> +    schema_pattern: AllowDenyPattern = AllowDenyPattern.allow_all()
Added.

2021-03-11 07:44 UTC, hsheth2 approved these changes
Looks great! Thanks for adding this.

2021-03-11 08:02 UTC, shirshanka approved these changes
LGTM!

2021-03-11 08:08 UTC, merged