Glue docs
linkedin/datahub pull request #2672
Opened 2021-06-09 22:35 UTC by kevinhu

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-06-10 17:24 UTC, hsheth2 requested changes

2021-06-10 17:24 UTC, hsheth2 commented on metadata-ingestion/s3-ingestion.md
> +    		- "avro"
indentation is off

2021-06-10 17:24 UTC, hsheth2 commented on metadata-ingestion/s3-ingestion.md
> +After ingesting, you should be able to see your datasets on the DataHub frontend.
maybe add a link to the full metadata ingestion docs?

2021-06-10 17:24 UTC, hsheth2 commented on metadata-ingestion/s3-ingestion.md
> +After ingesting, you should be able to see your datasets on the DataHub frontend.
and also add a link to this guide from the glue section of those docs

2021-06-14 19:34 UTC, hsheth2 approved these changes
LGTM!

2021-06-15 00:08 UTC, shirshanka approved these changes
Looks great. Thanks Kevin!

2021-06-15 00:08 UTC, merged