feat(ingest): extract lineage between SageMaker jobs and models
linkedin/datahub pull request #2868
Opened 2021-07-12 22:11 UTC by kevinhu

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2021-07-13 02:04 UTC, hsheth2 requested changes
minor nits but otherwise LGTM

2021-07-13 02:04 UTC, hsheth2 commented on metadata-ingestion/src/datahub/ingestion/source/sagemaker_processors/jobs.py
> +    job_direction: str  # 'training' or 'downstream'
this should probably be an enum

2021-07-13 18:55 UTC, hsheth2 approved these changes
LGTM!

2021-07-13 20:58 UTC, dexter-mh-lee approved these changes
LGTM!!

2021-07-16 01:56 UTC, shirshanka approved these changes
LGTM!

2021-07-16 01:56 UTC, merged