refactor(search): refactor NUM_RETRIES in esindexbuilder to be configurable
linkedin/datahub pull request #3870
Opened 2022-01-11 17:22 UTC by senni0418

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))

2022-01-11 18:37 UTC, senni0418 commented
This pull request is to make the NUM_RETRIES constant in the ESIndexBuilder configurable as an environment variable. The original number is set to 3 which causes the reindex failure when our team build the project. This is because our datahub has too many metadata to reindex and the NUM_RETRIES=3 is not enough for the project to be reindexed. In this case, we think other users in the community may face the same issue as well. So we decide to make this configurable so that the user can change the number as needed.

Here attach the log of reindex failure from our team for your reference.
[elastic-reindex-err-gms.log](https://github.com/linkedin/datahub/files/7849083/elastic-reindex-err-gms.log)

2022-01-11 22:14 UTC, dexter-mh-lee requested changes
Thanks for the contribution. So for env variables, we never change the dockerfiles directly because the variables are not easy to find. Instead we use factories that get variables from application.yaml. 

Check out this factory https://github.com/linkedin/datahub/blob/master/metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchIndexBuilderFactory.java that creates ESIndexBuilders for all our search services. You just need to expose the num retries as an input variable to the constructor and add a new injected variable in the factory similar to this https://github.com/linkedin/datahub/blob/master/metadata-service/factories/src/main/java/com/linkedin/gms/factory/search/ElasticSearchIndexBuilderFactory.java

Then, you can change the application.yaml file that the factory is picking up https://github.com/linkedin/datahub/blob/master/metadata-service/factories/src/main/resources/application.yml#L100 You can see that env variables with defaults are pushed into the application.yml file (and thus into the factory)

2022-01-12 16:22 UTC, senni0418 commented
Hi @dexter-mh-lee I have changed the way of refactor in the way you describe. feel free to add more comments if you have other concerns

2022-01-12 20:20 UTC, dexter-mh-lee commented on metadata-service/factories/src/main/resources/application.yml
> +    numRetries: ${ELASTICSEARCH_NUM_RETRIES_PER_INDEX:3}
nit: Can we rename this to ELASTICSEARCH_INDEX_BUILDER_NUM_RETRIES ?

2022-01-12 20:21 UTC, dexter-mh-lee approved these changes
LGTM. Minor comment to make sure the env variable is easy to understand!

2022-01-13 18:41 UTC, dexter-mh-lee approved these changes
LGTM! cc @shirshanka

2022-01-17 23:35 UTC, shirshanka approved these changes
LGTM

2022-01-17 23:35 UTC, merged