feat(ingest) Athena: Getting table properties for Athena datasets
linkedin/datahub pull request #4123
Opened 2022-02-11 10:26 UTC by treff7es

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-02-11 18:48 UTC, rslanka commented on metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
> +    cursor: Optional[BaseCursor] = None
Should this be at the class-scope or be an instance member?

2022-02-11 18:58 UTC, rslanka commented on metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
> +                for k, v in metadata.__dict__.items()
What exactly do we need here? Accessing `__dict__` seems quite risky here. Pretty much every private member seems to be accessible via the @property decorator.

2022-02-11 19:00 UTC, rslanka commented on metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
> +        if metadata.partition_keys:
This is an unnecessary check. Default value is an empty array.

2022-02-11 19:04 UTC, rslanka commented on metadata-ingestion/src/datahub/ingestion/source/sql/athena.py
> +                partition_key.append(key.__dict__)
What's going on here with key.__dict__? All of the members of `AthenaTableMetadataPartitionKey` are accessible via the @property decorator.

2022-02-11 19:08 UTC, rslanka requested changes
This needs an update. Please see comments for details.

2022-02-14 18:20 UTC, rslanka commented on metadata-ingestion/setup.py
> +    "athena": sql_common | {"PyAthena[SQLAlchemy]==2.4.1"},
Why `==` and not `>=`? Would this be the same as `pyathena>=2.4.1`?

2022-02-14 20:35 UTC, rslanka approved these changes
LGTM!

2022-02-14 20:35 UTC, rslanka commented on metadata-ingestion/setup.py
> +    "athena": sql_common | {"PyAthena[SQLAlchemy]==2.4.1"},
Ah! I see...we are using private APIs!

2022-02-14 21:51 UTC, shirshanka approved these changes
LGTM!

2022-02-14 21:51 UTC, merged