feat(ingest): add Python libs for Urns
linkedin/datahub pull request #4172
Opened 2022-02-17 21:49 UTC by tc350981

In the data model we define Urn as String which make it hard to manipulate. This PR creates python lib for Urn, DatasetUrn, DataPlatformUrn classes which is meant to help interact with Urn easier.
## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

2022-02-20 03:01 UTC, shirshanka requested changes
This is great work and will make working with Urns much nicer. Thanks!
Have a few suggestions for you. 

Also, how do you think we should transition from the `make_x_urn` pattern in `mce_builder.py`, since all connectors use that pathway today.

2022-02-22 21:00 UTC, tc350981 commented on metadata-ingestion/src/datahub/utilities/urns/dataset_urn.py
> +    def get_env(self) -> str:
That's a good point. But I am not quite familiar with Python. I tried my best to search online to find a clean way to get all values of FabricTypeClass. But did not make it. In the change I use something like 
```
VALID_FABRIC_SET: Set[str] = set(
        [
            str(getattr(FabricTypeClass, attr)).upper()
            for attr in dir(FabricTypeClass)
            if not callable(getattr(FabricTypeClass, attr)) and not attr.startswith("_")
        ]
    )
```

Please let me know if you have some suggestion about this

2022-02-23 00:37 UTC, tc350981 commented
> This is great work and will make working with Urns much nicer. Thanks! Have a few suggestions for you.
> 
> Also, how do you think we should transition from the `make_x_urn` pattern in `mce_builder.py`, since all connectors use that pathway today.

maybe we could do it in phases, like:
1. change the implementation of make_x_urn to use x Urn class
2. Use Urn classes in new code
3. Soft deprecate the make_x_urn util function

2022-02-23 01:18 UTC, shirshanka commented on metadata-ingestion/src/datahub/utilities/urns/dataset_urn.py
> +    def get_env(self) -> str:
Take a look at this : https://github.com/linkedin/datahub/blob/master/metadata-ingestion/src/datahub/configuration/source_common.py#L38

2022-02-23 01:51 UTC, tc350981 commented on metadata-ingestion/src/datahub/utilities/urns/dataset_urn.py
> +    def get_env(self) -> str:
@shirshanka ah thanks for replying. Looks like we are using the same logic

2022-02-23 03:38 UTC, shirshanka approved these changes
LGTM!

2022-02-23 03:39 UTC, merged